apiVersion: v1
kind: Service
metadata:
  name: document-management-postgres
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30205
  sessionAffinity: None
  type: NodePort