apiVersion: v2
name: document-management
description: Helm Chart for Document Management
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: postgres
    version: 0.0.1
    condition: postgres.enabled